org: daara
app: todo-escalator
service: todo-escalator

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9
  region: eu-west-2


functions:
  cronHandler:
    handler: todo_escalator.handler.lambda_handler
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0 8 * * ? *)
    environment:
      API_TOKEN: "your_api_token"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePoetry: true
    slim: true